version: "3"

networks:
  karma:
    external:
      name: karma

services:
  karma_app_backend:
    build: ./
    image: karma_app_backend:${APP_TAG}
    container_name: karma_app_backend
    hostname: karma_app_backend
    restart: on-failure
    networks:
      karma:
        ipv4_address: 192.168.240.25

